name = "peer-fitness-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "gymbro-db"
database_id = "35f8f5ce-0644-4a3f-a3e9-e8693f649df8"

[[kv_namespaces]]
binding = "KV"
id = "ee9db6d674b346bf9d746cc573906f99"

[[r2_buckets]]
binding = "R2"
bucket_name = "peer-fitness-images"

[[triggers]]
crons = ["0 9 * * *"]  # Daily at 9 AM UTC for streak resets and notifications

[vars]
# Environment variables
ENVIRONMENT = "development"
JWT_SECRET = "C1fhLUZA4dHYjJp6Vh0bksLBThJoRPpwUGkTj/D3kcyBZGJ9uWWfOIDDMuUWB/Ps0K9wcETzojFCKLJ/eSEZ3Q=="
GEMINI_API_KEY = "AIzaSyCua3FUDnURI3OH1wSlrNMqbX-wtnWSYHY"
SUPABASE_URL="https://koudzeojjkteioowweel.supabase.co/"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdWR6ZW9qamt0ZWlvb3d3ZWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MTEyODUsImV4cCI6MjA3NjI4NzI4NX0.yHHgFWIYy2RNDMd5VHSuOiHZYgrG3fmTXQr9crYRS-Q"
