name = "peer-fitness-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[d1_databases]]
binding = "DB"
database_name = "peer-fitness-db"
database_id = "your-database-id-here"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id-here"

[[r2_buckets]]
binding = "R2"
bucket_name = "peer-fitness-images"

[[triggers]]
crons = ["0 9 * * *"]  # Daily at 9 AM UTC for streak resets and notifications
